{
 "title": "Cloud Impact",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(awsregion)" } },
   { "name": "resource_type", "label": "Resource type", "query": { "query": "label_values(resource_type)" } },
   { "name": "tags_to_include", "label": "Tags to include" }
  ]
 },
 "panels": [
  {
   "title": "Introduction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 19, "x": 0, "y": 9 },
     "options": {
      "content": "\r\n<img style=\"float:right;height:42px;\" src=\"https://boavizta.org/media/site/d84925bc94-1642413712/boavizta-logo-4.png\"/> \r\n<strong>Boavizta Cloud-Scanner - Environmental impacts of EC2 instances and block storage</strong>"
     }
    },
    {
     "title": "Number of resources (taken into assessment)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
     "targets": [
      {
       "expr": "boavizta_number_of_resources_assessed",
       "legendFormat": "{{country}} ({{awsregion}})"
      }
     ]
    },
    {
     "title": "Explanations",
     "type": "text",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 11 },
     "options": {
      "content": "Cloud-scanner returns environmental impacts of your AWS usage.\n\nIt combines real time inventory and usage data from an AWS account with impact data from Boavizta API.\n\n## Resource considered\n\n- EC2 instances (type and CPU load)\n- Block storage (type and size)\n\n## Indicators\n\n- 🔥 Global Warming Potential - GWP (CO2eq)\n- ⚡ Primary Energy - PE (KWH or Mega Joules)\n- 🌍 Abiotic Depletion Potential - ADP: resources like mineral, water (kgSbeq)\n\n## Scopes\n\n- Use (displayed here for **one hour** of use)\n- Embodied impacts (i.e. manufacture related impacts, amortized for one hour of use)\n\n## Data and methodology\n\n- https://boavizta.github.io/cloud-scanner/\n- https://www.boavizta.org/en\n- https://boavizta.org/en/blog/empreinte-de-la-fabrication-d-un-serveur\n\n\n"
     }
    },
    {
     "title": "Number of resources - any state",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(country) (boavizta_resource_duration_of_use_hours{resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Type of resources",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(resource_type) (boavizta_resource_duration_of_use_hours)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of resources - Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(country) (boavizta_resource_duration_of_use_hours{resource_state!=\"Stopped\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Primary Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "⚡ Primary Energy (Use) for 1 hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (boavizta_resource_pe_use_megajoules{resource_tags=~\".*$tags_to_include.*\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (Embodied) - by region - projected for 1 year",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (Use) - by region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"} * 0.277778)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (Use) - by region - projected for 1 year",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Warming Potential",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔥 Global Warming Potential (Use) - for an hour  (Kg Co2 eq) ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\",resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "🔥 GWP (Use) - by region (Kg Co2 eq)  - projected for 1 year",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 10, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\",resource_tags=~\".*$tags_to_include.*\"}  ) * 24 * 365",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by(awsregion) (boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🔥 Global Warming Potential (Use) - by region (Kg Co2 eq) ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\",resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum by(awsregion) (boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🔥 GWP (Embodied) - by region (Kg Co2 eq)  - projection for 1 year",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 10, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_gwp_embodied_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by(awsregion) (boavizta_resource_gwp_embodied_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Abiotic Depletion Potential (ADP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "🌍ADP - Abiotic Depletion Potential (Use) - by region (Kg sb eq) ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum by(awsregion) (boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🌍ADP - Abiotic Depletion Potential (Embodied) - by region (Kg sb eq) ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "expr": "sum(boavizta_resource_adp_embodied_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
       "legendFormat": "total"
      },
      {
       "expr": "sum by(awsregion) (boavizta_resource_adp_embodied_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and storage metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "description": "CPU load of instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "boavizta_resource_cpu_load{awsregion=~\"$region\", resource_type=\"Instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Storage size (GB)",
     "type": "timeseries",
     "description": "Size of the volume, without considering if it is full or empty.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "boavizta_storage_size_gb{awsregion=~\"$region\", resource_type=~\"BlockStorage\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}