{
 "title": "Cloud impacts",
 "description": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(awsregion)" } },
   { "name": "resource_type", "label": "Resource type", "query": { "query": "label_values(resource_type)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<img style=\"float:right;height:42px;\" src=\"https://boavizta.org/media/site/d84925bc94-1642413712/boavizta-logo-4.png\"/> \r\n<strong>Boavizta Cloud-Scanner - Environmental impacts of EC2 instances and block storage</strong>"
   }
  },
  {
   "title": "⚡ Primary Energy (use) for 1 hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (boavizta_resource_pe_use_megajoules) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of resources - Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(country) (boavizta_resource_duration_of_use_hours{resource_state!=\"Stopped\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (Use) - by region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"} * 0.277778)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of resources - any state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(country) (boavizta_resource_duration_of_use_hours)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Type of resources",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(resource_type) (boavizta_resource_duration_of_use_hours)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔥 Global Warming Potential (Use) - by region (Kg Co2 eq) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of resources (taken into assessment)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "boavizta_number_of_resources_assessed",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "🌍ADP - Abiotic Depletion Potential (Use) - by region (Kg sb eq) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Explanations",
   "type": "text",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 18 },
   "options": {
    "content": "Cloud-scanner returns environmental impacts of your AWS usage.\n\nIt combines real time inventory and usage data from an AWS account with impact data from Boavizta API.\n\n## Resource considered\n\n- EC2 instances (type and CPU load)\n- Block storage (type and size)\n\n## Indicators\n\n- 🔥 Global Warming Potential - GWP (CO2eq)\n- ⚡ Primary Energy - PE (KWH or Mega Joules)\n- 🌍 Abiotic Depletion Potential - ADP: reousrces like mineral, water (kgSbeq)\n\n## Scopes\n\n- Use (displayed here for **one hour** of use)\n- Embodied impacts (i.e. manufacture related impacts, amortized for one hour of use)\n\n## Data and methodology\n\n- https://boavizta.github.io/cloud-scanner/\n- https://www.boavizta.org/en\n- https://boavizta.org/en/blog/empreinte-de-la-fabrication-d-un-serveur\n\n\n"
   }
  },
  {
   "title": "🔥 Global Warming Potential (Embodied) - by region (Kg Co2 eq) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778 * 24 * 365 * 5",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (embodied) - by region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778 * 24 * 365",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(awsregion) (boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}