{
 "title": "Environmental Impacts of Cloud",
 "description": "Environmental impacts of aws EC2 instances per region",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<img style=\"float:right;height:42px;\" src=\"https://boavizta.org/media/site/d84925bc94-1642413712/boavizta-logo-4.png\"/> \r\n<strong>Boavizta Cloud-Scanner - Environmental impacts of EC2 instances</strong>"
   }
  },
  {
   "title": "Energy used for 1 hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_pe_use_megajoules * 0.277778",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Explanations",
   "type": "text",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 2 },
   "options": {
    "content": "Cloud-scanner returns environmental impacts of your AWS Instances usage.\n\nIt combines real time usage data from your AWS account with Boavizta API to offer a global view of your impacts on a given region.\n\n## Indicators\n\n- 🔥 Global Warming Potential - GWP (CO2eq)\n- ⚡ Primary Energy - PE (KWH or Mega Joules)\n- 🌍 Abiotic Depletion Potential - ADP: reousrces like mineral, water (kgSbeq)\n\n## Scopes\n\n- Use (displayed here for **one hour** of use)\n- Manufacture (displayed here for the entire server lifecyle, not amortized)\n\n## Data and methodology\n\n- https://boavizta.github.io/cloud-scanner/\n- https://www.boavizta.org/en\n- https://boavizta.org/en/blog/empreinte-de-la-fabrication-d-un-serveur\n\n\n"
   }
  },
  {
   "title": "Number of resources assessed",
   "type": "stat",
   "description": "Number of instances really taken into account for impact calculations (some instance types have no data in Boavizta dataset).",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_number_of_resources_assessed",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Number of resources total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_number_of_resources_total",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Number of resources (taken into assessment)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "boavizta_number_of_resources_assessed",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Primary Energy (Use) MJ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "targets": [
    { "expr": "boavizta_pe_use_megajoules", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Primary Energy (Use) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_pe_use_megajoules", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Primary Energy (Manufacture) - entire lifetime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MJ" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_pe_manufacture_megajoules",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Global Warming Potential (Use) in kgco2eq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": " kgco2eq" } },
   "targets": [
    { "expr": "boavizta_gwp_use_kgco2eq", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Global Warming Potential (Use) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kgco2eq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_gwp_use_kgco2eq", "legendFormat": "{{country}} ({{awsregion}})" }
   ]
  },
  {
   "title": "Global Warming Potential (Manufacture)  - entire lifetime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kgco2eq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_gwp_manufacture_kgco2eq",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Abiotic Depletion Potential (Manufacture) kgsbeq",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "targets": [
    {
     "expr": "boavizta_adp_manufacture_kgsbeq",
     "legendFormat": "{{country}} ({{awsregion}})"
    }
   ]
  },
  {
   "title": "Abiotic Depletion ¨Potential (Use) / Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "boavizta_adp_use_kgsbeq", "legendFormat": "{{awsregion}}" }
   ]
  },
  {
   "title": "Abiotic Depletion Potential (Manufacture)  - entire lifetime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kgsbeq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boavizta_adp_manufacture_kgsbeq",
     "legendFormat": "{{awsregion}}"
    }
   ]
  }
 ]
}