{
 "title": "Cloud Eco impacts - Kubernetes namespace monitoring",
 "description": "Monitors Environmental Impacts Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(awsregion)" } },
   { "name": "resource_type", "label": "Resource type", "query": { "query": "label_values(resource_type)" } },
   { "name": "resource_id", "query": { "query": "label_values(resource_id)" } },
   { "name": "tags_to_include", "label": "Tags to include" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<img style=\"float:right;height:42px;\" src=\"https://boavizta.org/media/site/d84925bc94-1642413712/boavizta-logo-4.png\"/> \r\n<strong>Boavizta Cloud-Scanner - Environmental impacts of namespace \"taxng\" in Kubernetes cluster \"pm2dev2\"</strong>"
   }
  },
  {
   "title": "⚡ Primary Energy (Use) - by pods",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"} * 0.277778)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_pe_use_megajoules{awsregion=~\"$region\", resource_id=~\"$resource_id\", resource_type=~\"$resource_type\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ Primary Energy (embodied) - by pod (5 year)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365 * 5",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_pe_embodied_megajoules{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 0.277778 * 24 * 365 * 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔥 Global Warming Potential (Use) - by pod (Kg Co2 eq) ",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_gwp_use_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔥 Global Warming Potential (Embodied) - by pod (Kg Co2 eq)  - 5 years",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_gwp_embodied_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_gwp_embodied_kgco2eq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌍ADP - Abiotic Depletion Potential (Use) - by pod (Kg sb eq) ",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_adp_use_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌍ADP - Abiotic Depletion Potential (Embodied) - by pod (Kg sb eq) - 5 years",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum(boavizta_resource_adp_embodied_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(resource_id) (boavizta_resource_adp_embodied_kgsbeq{awsregion=~\"$region\", resource_type=~\"$resource_type\", resource_id=~\"$resource_id\", resource_tags=~\".*$tags_to_include.*\"}) * 24 * 365 * 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Explanations",
   "type": "text",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 62 },
   "options": {
    "content": "Cloud-scanner returns environmental impacts of your AWS usage.\n\nIt combines real time inventory and usage data from an AWS account with impact data from Boavizta API.\n\n## Resource considered\n\n- EC2 instances (type and CPU load)\n- Block storage (type and size)\n\n## Indicators\n\n- 🔥 Global Warming Potential - GWP (CO2eq)\n- ⚡ Primary Energy - PE (KWH or Mega Joules)\n- 🌍 Abiotic Depletion Potential - ADP: reousrces like mineral, water (kgSbeq)\n\n## Scopes\n\n- Use (displayed here for **one hour** of use)\n- Embodied impacts (i.e. manufacture related impacts, amortized for one hour of use)\n\n## Data and methodology\n\n- https://boavizta.github.io/cloud-scanner/\n- https://www.boavizta.org/en\n- https://boavizta.org/en/blog/empreinte-de-la-fabrication-d-un-serveur\n\n\n"
   }
  }
 ]
}