/*
 * BOAVIZTAPI - DEMO
 *
 * # 🎯 Retrieving the impacts of digital elements This is a quick demo, to see full documentation [click here](http://api.boavizta.org)  ## ➡️Server router  ### Server routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |     X    | |   ADP  |        X       |     X    | |   PE   |        X       |     X    | ## ➡️Cloud router  ### Cloud routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |     X    | |   ADP  |        X       |     X    | |   PE   |        X       |     X    | ## ➡️Component router  ### Component routers support the following impacts:  | Impact | 🔨 Manufacture | 🔌 Usage | |--------|----------------|----------| |   GWP  |        X       |          | |   ADP  |        X       |          | |   PE   |        X       |          | 
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigurationServer {
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Box<crate::models::Cpu>>,
    #[serde(rename = "ram", skip_serializing_if = "Option::is_none")]
    pub ram: Option<Vec<crate::models::Ram>>,
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<Vec<crate::models::Disk>>,
    #[serde(rename = "power_supply", skip_serializing_if = "Option::is_none")]
    pub power_supply: Option<Box<crate::models::PowerSupply>>,
}

impl ConfigurationServer {
    pub fn new() -> ConfigurationServer {
        ConfigurationServer {
            cpu: None,
            ram: None,
            disk: None,
            power_supply: None,
        }
    }
}


