@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml



LAYOUT_WITH_LEGEND()

Person(ana, "Ana", "Manage resources in an AWS account")


System(cloudscanner, "Cloud scanner", "Collects resource usage data in a format usable to query Boavizta API", "a")

System_Ext(boaviztaapi, "Boavizta API", "Returns impact data")
System_Ext(aws, "aws standard apis", "Returns resource usage")


Rel(ana, cloudscanner, "Get cloud usage data using")
Rel(ana, boaviztaapi, "Get impacts of the scanned resources using")
Rel(cloudscanner,aws, "List resources and usage detail using")



@enduml